version: '3.8'
services:
  backend:
    build: ./travel
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./travel/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev


  my-react-app:
    build:
      context: ./my-react-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./my-react-app:/app
      - /app/node_modules
    command: npm run dev -- --host
    environment:
      - CHOKIDAR_USEPOLLING=true